"""initial migration

Revision ID: 54d37ad7c029
Revises: 
Create Date: 2022-09-30 12:39:35.560005

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '54d37ad7c029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('country',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('state',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('addr', sa.String(length=100), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('state_id', sa.Integer(), nullable=True),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.Column('pin', sa.String(length=100), nullable=True),
                    sa.Column('roll_no', sa.String(length=100), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
                    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
                    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('state')
    op.drop_table('country')
    op.drop_table('city')
    # ### end Alembic commands ###
