"""ADDED RELATION BTW CITY, STATE, COUNTRY

Revision ID: 98299c6a52b5
Revises: 54d37ad7c029
Create Date: 2022-09-30 12:40:48.546487

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98299c6a52b5'
down_revision = '54d37ad7c029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_city_state_id_state', 'state', ['state_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_city_country_id_country', 'country', ['country_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_state_country_id_country', 'country', ['country_id'], ['id'],
                                    ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_id')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_id')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
