"""added standard column in student table

Revision ID: e3e49db28e3c
Revises: 98299c6a52b5
Create Date: 2022-10-03 13:48:24.198618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e49db28e3c'
down_revision = '98299c6a52b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint('fk_city_country_id_country', type_='foreignkey')
        batch_op.drop_constraint('fk_city_state_id_state', type_='foreignkey')
        batch_op.create_foreign_key('fk_city_state_id_state', 'state', ['state_id'], ['id'])
        batch_op.create_foreign_key('fk_city_country_id_country', 'country', ['country_id'], ['id'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_state_country_id_country', type_='foreignkey')
        batch_op.create_foreign_key('fk_state_country_id_country', 'country', ['country_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('standard')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_state_country_id_country', 'country', ['country_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_city_state_id_state', 'state', ['state_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_city_country_id_country', 'country', ['country_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
